### ISSUE TITLE
Crash after launching the game

### ISSUE THREAD

**Issue by ainlzj** [AlfheimOnlineMC/AlfheimModUpdated#1]
[minecraft-exported-crash-info-2022-07-15T00-11-42.zip](https://github.com/AlfheimOnlineMC/AlfheimModUpdated/files/9113484/minecraft-exported-crash-info-2022-07-15T00-11-42.zip)

**Comment by AugmaTV** [comment]
i'll check that

**Comment by AugmaTV** [comment]
i've fixed it and upload the fix on curseforge if you can test again when it will be approved :)

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/179032605-63b534ca-2f47-4d2c-9e83-7d75d9fc13ba.png)

**Comment by AugmaTV** [comment]
ah xD i forgot to remove that thing, it was a test

**Comment by AugmaTV** [comment]
thank's

**Comment by AugmaTV** [comment]
it's removed and upload on curseforge, thank's again :)

**Comment by AugmaTV** [comment]
i'll close this issue, if you find something weird like that i give you my discord : Augma#4544 cya :)
